### ISSUE TITLE
Submit button disappears with to much text

### ISSUE THREAD

**Issue by MonteChristo46** [rsmttud/Recommender-System#1]
Submit button disappears with to much text

**Comment by rsmttud** [comment]
Should try min-height: 100vh in css according to: https://stackoverflow.com/questions/37031350/full-page-column-in-materialize-css

**Comment by RichardHorn** [comment]
Should try min-height: 100vh in css according to: https://stackoverflow.com/questions/37031350/full-page-column-in-materialize-css

**Comment by RichardHorn** [comment]
solved
